# Generated by Django 2.0.5 on 2018-05-04 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 5, 4, 9, 49, 57, 612750), verbose_name='Опубликована'),
        ),
    ]
