# Generated by Django 2.0.5 on 2018-05-04 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180504_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 5, 4, 9, 59, 29, 860120), verbose_name='Опубликована'),
        ),
    ]
