# Generated by Django 2.0.5 on 2018-05-04 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180504_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 5, 4, 14, 18, 3, 700054), verbose_name='Опубликована'),
        ),
    ]
