# Generated by Django 2.0.5 on 2018-05-07 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180504_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 5, 7, 8, 56, 7, 473959), verbose_name='Опубликована'),
        ),
    ]
