# Generated by Django 2.0.5 on 2018-05-08 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20180507_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 5, 8, 9, 13, 36, 523311), verbose_name='Опубликована'),
        ),
    ]
