# Generated by Django 2.0.5 on 2018-05-08 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20180508_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 5, 8, 10, 1, 6, 682127), verbose_name='Опубликована'),
        ),
    ]
