# Generated by Django 2.0.5 on 2018-05-08 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 5, 8, 12, 43, 27, 708301), verbose_name='Опубликована'),
        ),
    ]
