# Generated by Django 2.0.5 on 2018-05-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterModelOptions(
            name='goodimage',
            options={'verbose_name': 'изображение к товару', 'verbose_name_plural': 'изображения к товару'},
        ),
        migrations.AlterField(
            model_name='good',
            name='featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Рекомендуемый'),
        ),
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(upload_to='goods/list', verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='good',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.FloatField(db_index=True, verbose_name='Цена, руб.'),
        ),
        migrations.AlterField(
            model_name='good',
            name='price_acc',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена с учетом скидки, руб.'),
        ),
        migrations.AlterField(
            model_name='goodimage',
            name='image',
            field=models.ImageField(upload_to='goods/detail', verbose_name='Дополнительное изображение'),
        ),
    ]
